# Generated by Django 4.0.3 on 2022-03-05 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=20)),
                ('_long', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('wifi', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=25)),
                ('outdoor', models.BooleanField()),
                ('installDate', models.DateTimeField()),
                ('rt', models.IntegerField()),
                ('rw', models.IntegerField()),
                ('fo', models.BooleanField()),
                ('note', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint_UpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.inventorytype')),
            ],
        ),
        migrations.CreateModel(
            name='Action_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint_UpDownLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.accesspoint')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPoint_EditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.accesspoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.area'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='converter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converter', to='polls.inventory'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router', to='polls.inventory'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.accesspoint_uplog'),
        ),
    ]
