# Generated by Django 4.0.3 on 2022-03-07 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='linka',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='linka2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='linkb',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aparea', to='polls.area'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='converter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converterap', to='polls.inventory'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='installDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routerap', to='polls.inventory'),
        ),
        migrations.AlterField(
            model_name='accesspoint_editlog',
            name='ap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apeditlog', to='polls.accesspoint'),
        ),
        migrations.AlterField(
            model_name='accesspoint_editlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usereditlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesspoint_updownlog',
            name='ap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apdownlog', to='polls.accesspoint'),
        ),
        migrations.AlterField(
            model_name='action_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useractionlog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeinventory', to='polls.inventorytype'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissiongroup', to='auth.group'),
        ),
    ]
