# Generated by Django 4.0.3 on 2022-03-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_accesspoint_linka_accesspoint_linka2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='installDate',
            new_name='date',
        ),
    ]
