# Generated by Django 4.0.3 on 2022-03-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_installdate_accesspoint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='linkb2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
