# Generated by Django 4.0.3 on 2022-03-09 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_accesspoint_linkb2'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='_createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='date',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
